[package]
name = "iced_text_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", rev = "refs/tags/text-editor", features = ["debug", "tokio", "highlighter"]}
tokio = { version = "1.40.0", features = ["fs"]}
rfd = "0.15.0"
